// apps/web/src/components/chat/UploadProgressBadge.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(
  defineProps<{
    progress?: number;
    status?: 'uploading' | 'error';
    size?: number;
  }>(),
  {
    progress: 0,
    status: 'uploading',
    size: 24,
  }
);

const normalizedProgress = computed(() => {
  if (!Number.isFinite(props.progress)) return 0;
  return Math.max(0, Math.min(99, Math.round(props.progress)));
});

const badgeStyle = computed(() => ({
  inlineSize: `${props.size}px`,
  blockSize: `${props.size}px`,
}));

const strokeWidth = computed(() => (props.size <= 24 ? 2 : 2.25));
const center = computed(() => props.size / 2);
const radius = computed(() =>
  Math.max(0, (props.size - strokeWidth.value - 1) / 2)
);
const circumference = computed(() => 2 * Math.PI * radius.value);
const strokeDashoffset = computed(
  () =>
    circumference.value - (normalizedProgress.value / 100) * circumference.value
);
const ringTransform = computed(
  () => `rotate(-90 ${center.value} ${center.value})`
);
</script>

<template>
  <div
    class="upload-progress-badge"
    :class="{ 'upload-progress-badge--error': status === 'error' }"
    :style="badgeStyle"
    aria-live="polite"
  >
    <svg
      class="upload-progress-badge__ring"
      :width="size"
      :height="size"
      :viewBox="`0 0 ${size} ${size}`"
      aria-hidden="true"
    >
      <circle
        class="upload-progress-badge__track"
        :class="{ 'upload-progress-badge__track--error': status === 'error' }"
        :cx="center"
        :cy="center"
        :r="radius"
        :stroke-width="strokeWidth"
      />
      <circle
        class="upload-progress-badge__value"
        :class="{ 'upload-progress-badge__value--error': status === 'error' }"
        :cx="center"
        :cy="center"
        :r="radius"
        :stroke-width="strokeWidth"
        :stroke-dasharray="`${circumference} ${circumference}`"
        :stroke-dashoffset="status === 'error' ? 0 : strokeDashoffset"
        :transform="ringTransform"
      />
    </svg>
    <span v-if="status !== 'error'" class="upload-progress-badge__label">
      {{ normalizedProgress }}%
    </span>
    <VIcon v-else size="14" color="error">tabler-alert-circle</VIcon>
  </div>
</template>

<style scoped>
.upload-progress-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  position: relative;
  border-radius: 50%;
  background: rgba(var(--v-theme-surface), 0.95);
  box-shadow: 0 1px 5px rgba(var(--v-theme-on-surface), 0.12);
  color: rgb(var(--v-theme-primary));
  overflow: hidden;
  pointer-events: none;
}

.upload-progress-badge--error {
  background: rgba(var(--v-theme-surface), 0.96);
  color: rgb(var(--v-theme-error));
}

.upload-progress-badge__label {
  position: relative;
  z-index: 1;
  color: rgb(var(--v-theme-primary));
  font-size: 0.47rem;
  font-weight: 800;
  letter-spacing: 0;
  line-height: 1;
  text-align: center;
}

.upload-progress-badge--error .upload-progress-badge__label {
  color: rgb(var(--v-theme-error));
}

.upload-progress-badge__ring {
  position: absolute;
  inset: 0;
}

.upload-progress-badge__track,
.upload-progress-badge__value {
  fill: none;
}

.upload-progress-badge__track {
  stroke: rgba(var(--v-theme-primary), 0.18);
}

.upload-progress-badge__track--error {
  stroke: rgba(var(--v-theme-error), 0.2);
}

.upload-progress-badge__value {
  stroke: rgb(var(--v-theme-primary));
  stroke-linecap: round;
  transition: stroke-dashoffset 160ms ease;
}

.upload-progress-badge__value--error {
  stroke: rgb(var(--v-theme-error));
}
</style>

// apps/mobile/components/UploadProgressBadge.tsx
import type { StyleProp, ViewStyle } from 'react-native';
import { StyleSheet, Text, View } from 'react-native';
import Svg, { Circle } from 'react-native-svg';
import { colors } from '../theme/colors';
import type { UploadProgressStatus } from '../types/uploadProgress';

type UploadProgressBadgeProps = {
  progress: number;
  status?: UploadProgressStatus;
  size?: number;
  style?: StyleProp<ViewStyle>;
};

const STROKE_WIDTH = 3;

function clampProgress(progress: number): number {
  if (!Number.isFinite(progress)) return 0;
  return Math.max(0, Math.min(99, Math.round(progress)));
}

export function UploadProgressBadge({
  progress,
  status = 'uploading',
  size = 38,
  style,
}: UploadProgressBadgeProps) {
  const normalizedProgress = clampProgress(progress);
  const radius = (size - STROKE_WIDTH * 2) / 2;
  const center = size / 2;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset =
    circumference - (normalizedProgress / 100) * circumference;
  const isError = status === 'error';

  return (
    <View
      pointerEvents="none"
      style={[
        styles.badge,
        {
          width: size,
          height: size,
          borderRadius: size / 2,
        },
        isError && styles.badgeError,
        style,
      ]}
    >
      <Svg width={size} height={size} style={StyleSheet.absoluteFill}>
        <Circle
          cx={center}
          cy={center}
          r={radius}
          stroke={
            isError ? 'rgba(255, 255, 255, 0.55)' : 'rgba(255, 255, 255, 0.45)'
          }
          strokeWidth={STROKE_WIDTH}
          fill="transparent"
        />
        <Circle
          cx={center}
          cy={center}
          r={radius}
          stroke={isError ? colors.error : colors.primaryDarken1}
          strokeWidth={STROKE_WIDTH}
          strokeLinecap="round"
          strokeDasharray={`${circumference} ${circumference}`}
          strokeDashoffset={isError ? 0 : strokeDashoffset}
          fill="transparent"
          originX={center}
          originY={center}
          rotation="-90"
        />
      </Svg>
      <Text style={styles.label}>
        {isError ? '!' : `${normalizedProgress}%`}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  badge: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(47, 43, 61, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.72)',
    overflow: 'hidden',
  },
  badgeError: {
    backgroundColor: 'rgba(255, 76, 81, 0.9)',
  },
  label: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    includeFontPadding: false,
    lineHeight: 12,
    textAlign: 'center',
  },
});
